/* 
 * CyberSource Flex API
 *
 * Simple PAN tokenization service
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace CyberSource.Model
{
    /// <summary>
    /// InlineResponse20012DeviceInformation
    /// </summary>
    [DataContract]
    public partial class InlineResponse20012DeviceInformation :  IEquatable<InlineResponse20012DeviceInformation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20012DeviceInformation" /> class.
        /// </summary>
        /// <param name="IpAddress">IP address of the customer..</param>
        /// <param name="HostName">DNS resolved hostname from above _ipAddress_..</param>
        /// <param name="CookiesAccepted">The description for this field is not available..</param>
        public InlineResponse20012DeviceInformation(string IpAddress = default(string), string HostName = default(string), string CookiesAccepted = default(string))
        {
            this.IpAddress = IpAddress;
            this.HostName = HostName;
            this.CookiesAccepted = CookiesAccepted;
        }
        
        /// <summary>
        /// IP address of the customer.
        /// </summary>
        /// <value>IP address of the customer.</value>
        [DataMember(Name="ipAddress", EmitDefaultValue=false)]
        public string IpAddress { get; set; }

        /// <summary>
        /// DNS resolved hostname from above _ipAddress_.
        /// </summary>
        /// <value>DNS resolved hostname from above _ipAddress_.</value>
        [DataMember(Name="hostName", EmitDefaultValue=false)]
        public string HostName { get; set; }

        /// <summary>
        /// The description for this field is not available.
        /// </summary>
        /// <value>The description for this field is not available.</value>
        [DataMember(Name="cookiesAccepted", EmitDefaultValue=false)]
        public string CookiesAccepted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20012DeviceInformation {\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  HostName: ").Append(HostName).Append("\n");
            sb.Append("  CookiesAccepted: ").Append(CookiesAccepted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InlineResponse20012DeviceInformation);
        }

        /// <summary>
        /// Returns true if InlineResponse20012DeviceInformation instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse20012DeviceInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20012DeviceInformation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.IpAddress == other.IpAddress ||
                    this.IpAddress != null &&
                    this.IpAddress.Equals(other.IpAddress)
                ) && 
                (
                    this.HostName == other.HostName ||
                    this.HostName != null &&
                    this.HostName.Equals(other.HostName)
                ) && 
                (
                    this.CookiesAccepted == other.CookiesAccepted ||
                    this.CookiesAccepted != null &&
                    this.CookiesAccepted.Equals(other.CookiesAccepted)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.IpAddress != null)
                    hash = hash * 59 + this.IpAddress.GetHashCode();
                if (this.HostName != null)
                    hash = hash * 59 + this.HostName.GetHashCode();
                if (this.CookiesAccepted != null)
                    hash = hash * 59 + this.CookiesAccepted.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IpAddress (string) maxLength
            if(this.IpAddress != null && this.IpAddress.Length > 15)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for IpAddress, length must be less than 15.", new [] { "IpAddress" });
            }

            // HostName (string) maxLength
            if(this.HostName != null && this.HostName.Length > 60)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for HostName, length must be less than 60.", new [] { "HostName" });
            }

            yield break;
        }
    }

}
