/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CyberSource.Client.SwaggerDateConverter;

namespace CyberSource.Model
{
    /// <summary>
    /// InlineResponseDefaultLinks
    /// </summary>
    [DataContract]
    public partial class InlineResponseDefaultLinks :  IEquatable<InlineResponseDefaultLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponseDefaultLinks" /> class.
        /// </summary>
        /// <param name="Next">Next.</param>
        /// <param name="Documentation">Documentation.</param>
        /// <param name="Self">Self.</param>
        public InlineResponseDefaultLinks(List<InlineResponseDefaultLinksNext> Next = default(List<InlineResponseDefaultLinksNext>), List<InlineResponseDefaultLinksNext> Documentation = default(List<InlineResponseDefaultLinksNext>), InlineResponseDefaultLinksNext Self = default(InlineResponseDefaultLinksNext))
        {
            this.Next = Next;
            this.Documentation = Documentation;
            this.Self = Self;
        }
        
        /// <summary>
        /// Gets or Sets Next
        /// </summary>
        [DataMember(Name="next", EmitDefaultValue=false)]
        public List<InlineResponseDefaultLinksNext> Next { get; set; }

        /// <summary>
        /// Gets or Sets Documentation
        /// </summary>
        [DataMember(Name="documentation", EmitDefaultValue=false)]
        public List<InlineResponseDefaultLinksNext> Documentation { get; set; }

        /// <summary>
        /// Gets or Sets Self
        /// </summary>
        [DataMember(Name="self", EmitDefaultValue=false)]
        public InlineResponseDefaultLinksNext Self { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponseDefaultLinks {\n");
            sb.Append("  Next: ").Append(Next).Append("\n");
            sb.Append("  Documentation: ").Append(Documentation).Append("\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InlineResponseDefaultLinks);
        }

        /// <summary>
        /// Returns true if InlineResponseDefaultLinks instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponseDefaultLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponseDefaultLinks other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Next == other.Next ||
                    this.Next != null &&
                    this.Next.SequenceEqual(other.Next)
                ) && 
                (
                    this.Documentation == other.Documentation ||
                    this.Documentation != null &&
                    this.Documentation.SequenceEqual(other.Documentation)
                ) && 
                (
                    this.Self == other.Self ||
                    this.Self != null &&
                    this.Self.Equals(other.Self)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Next != null)
                    hash = hash * 59 + this.Next.GetHashCode();
                if (this.Documentation != null)
                    hash = hash * 59 + this.Documentation.GetHashCode();
                if (this.Self != null)
                    hash = hash * 59 + this.Self.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
