/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CyberSource.Client.SwaggerDateConverter;

namespace CyberSource.Model
{
    /// <summary>
    /// ReportingV3RetrievalDetailsGet200Response
    /// </summary>
    [DataContract]
    public partial class ReportingV3RetrievalDetailsGet200Response :  IEquatable<ReportingV3RetrievalDetailsGet200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportingV3RetrievalDetailsGet200Response" /> class.
        /// </summary>
        /// <param name="OrganizationId">Organization Id.</param>
        /// <param name="StartTime">Report Start Date (ISO 8601 Extended).</param>
        /// <param name="EndTime">Report Start Date (ISO 8601 Extended).</param>
        /// <param name="RetrievalDetails">List of Retrieval Details list..</param>
        public ReportingV3RetrievalDetailsGet200Response(string OrganizationId = default(string), DateTime? StartTime = default(DateTime?), DateTime? EndTime = default(DateTime?), List<ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails> RetrievalDetails = default(List<ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails>))
        {
            this.OrganizationId = OrganizationId;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
            this.RetrievalDetails = RetrievalDetails;
        }
        
        /// <summary>
        /// Organization Id
        /// </summary>
        /// <value>Organization Id</value>
        [DataMember(Name="organizationId", EmitDefaultValue=false)]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Report Start Date (ISO 8601 Extended)
        /// </summary>
        /// <value>Report Start Date (ISO 8601 Extended)</value>
        [DataMember(Name="startTime", EmitDefaultValue=false)]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// Report Start Date (ISO 8601 Extended)
        /// </summary>
        /// <value>Report Start Date (ISO 8601 Extended)</value>
        [DataMember(Name="endTime", EmitDefaultValue=false)]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// List of Retrieval Details list.
        /// </summary>
        /// <value>List of Retrieval Details list.</value>
        [DataMember(Name="retrievalDetails", EmitDefaultValue=false)]
        public List<ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails> RetrievalDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReportingV3RetrievalDetailsGet200Response {\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  RetrievalDetails: ").Append(RetrievalDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ReportingV3RetrievalDetailsGet200Response);
        }

        /// <summary>
        /// Returns true if ReportingV3RetrievalDetailsGet200Response instances are equal
        /// </summary>
        /// <param name="other">Instance of ReportingV3RetrievalDetailsGet200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReportingV3RetrievalDetailsGet200Response other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.OrganizationId == other.OrganizationId ||
                    this.OrganizationId != null &&
                    this.OrganizationId.Equals(other.OrganizationId)
                ) && 
                (
                    this.StartTime == other.StartTime ||
                    this.StartTime != null &&
                    this.StartTime.Equals(other.StartTime)
                ) && 
                (
                    this.EndTime == other.EndTime ||
                    this.EndTime != null &&
                    this.EndTime.Equals(other.EndTime)
                ) && 
                (
                    this.RetrievalDetails == other.RetrievalDetails ||
                    this.RetrievalDetails != null &&
                    this.RetrievalDetails.SequenceEqual(other.RetrievalDetails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.OrganizationId != null)
                    hash = hash * 59 + this.OrganizationId.GetHashCode();
                if (this.StartTime != null)
                    hash = hash * 59 + this.StartTime.GetHashCode();
                if (this.EndTime != null)
                    hash = hash * 59 + this.EndTime.GetHashCode();
                if (this.RetrievalDetails != null)
                    hash = hash * 59 + this.RetrievalDetails.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
