/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CyberSource.Client.SwaggerDateConverter;

namespace CyberSource.Model
{
    /// <summary>
    /// An object containing the count of completed payment cycles by status.
    /// </summary>
    [DataContract]
    public partial class GetSubscriptionsPaymentsResponseCyclesCompletedCount :  IEquatable<GetSubscriptionsPaymentsResponseCyclesCompletedCount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSubscriptionsPaymentsResponseCyclesCompletedCount" /> class.
        /// </summary>
        /// <param name="Paid">The number of payment cycles that have status PAID..</param>
        public GetSubscriptionsPaymentsResponseCyclesCompletedCount(int? Paid = default(int?))
        {
            this.Paid = Paid;
        }
        
        /// <summary>
        /// The number of payment cycles that have status PAID.
        /// </summary>
        /// <value>The number of payment cycles that have status PAID.</value>
        [JsonPropertyName("paid")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int? Paid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetSubscriptionsPaymentsResponseCyclesCompletedCount {\n");
            if (Paid != null) sb.Append("  Paid: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("GetSubscriptionsPaymentsResponseCyclesCompletedCount", "paid", Paid.ToString())).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskSensitiveDataInJson("GetSubscriptionsPaymentsResponseCyclesCompletedCount", JsonSerializer.Serialize(this, CyberSource.Utilities.Serialization.ModelLevelSerializerOptions.ToJsonOptions));
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetSubscriptionsPaymentsResponseCyclesCompletedCount);
        }

        /// <summary>
        /// Returns true if GetSubscriptionsPaymentsResponseCyclesCompletedCount instances are equal
        /// </summary>
        /// <param name="other">Instance of GetSubscriptionsPaymentsResponseCyclesCompletedCount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetSubscriptionsPaymentsResponseCyclesCompletedCount other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Paid == other.Paid ||
                    this.Paid != null &&
                    this.Paid.Equals(other.Paid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Paid != null)
                    hash = hash * 59 + this.Paid.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
