/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CyberSource.Client.SwaggerDateConverter;

namespace CyberSource.Model
{
    /// <summary>
    /// Attachment data.
    /// </summary>
    [DataContract]
    public partial class Iccv1instructionsinstructionIdcredentialsAttachments :  IEquatable<Iccv1instructionsinstructionIdcredentialsAttachments>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Iccv1instructionsinstructionIdcredentialsAttachments" /> class.
        /// </summary>
        /// <param name="Name">Type/Name of the image. For example - product, payment confirmation, cart etc..</param>
        /// <param name="ContentType">Content Type of the image. For example - image/jpeg, image/png, application/pdf etc..</param>
        /// <param name="Content">Image(Binary) in Base64 encoded with no padding..</param>
        public Iccv1instructionsinstructionIdcredentialsAttachments(string Name = default(string), string ContentType = default(string), string Content = default(string))
        {
            this.Name = Name;
            this.ContentType = ContentType;
            this.Content = Content;
        }
        
        /// <summary>
        /// Type/Name of the image. For example - product, payment confirmation, cart etc.
        /// </summary>
        /// <value>Type/Name of the image. For example - product, payment confirmation, cart etc.</value>
        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Name { get; set; }

        /// <summary>
        /// Content Type of the image. For example - image/jpeg, image/png, application/pdf etc.
        /// </summary>
        /// <value>Content Type of the image. For example - image/jpeg, image/png, application/pdf etc.</value>
        [JsonPropertyName("contentType")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ContentType { get; set; }

        /// <summary>
        /// Image(Binary) in Base64 encoded with no padding.
        /// </summary>
        /// <value>Image(Binary) in Base64 encoded with no padding.</value>
        [JsonPropertyName("content")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Content { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Iccv1instructionsinstructionIdcredentialsAttachments {\n");
            if (Name != null) sb.Append("  Name: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("Iccv1instructionsinstructionIdcredentialsAttachments", "name", Name.ToString())).Append("\n");
            if (ContentType != null) sb.Append("  ContentType: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("Iccv1instructionsinstructionIdcredentialsAttachments", "contentType", ContentType.ToString())).Append("\n");
            if (Content != null) sb.Append("  Content: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("Iccv1instructionsinstructionIdcredentialsAttachments", "content", Content.ToString())).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskSensitiveDataInJson("Iccv1instructionsinstructionIdcredentialsAttachments", JsonSerializer.Serialize(this, CyberSource.Utilities.Serialization.ModelLevelSerializerOptions.ToJsonOptions));
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Iccv1instructionsinstructionIdcredentialsAttachments);
        }

        /// <summary>
        /// Returns true if Iccv1instructionsinstructionIdcredentialsAttachments instances are equal
        /// </summary>
        /// <param name="other">Instance of Iccv1instructionsinstructionIdcredentialsAttachments to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Iccv1instructionsinstructionIdcredentialsAttachments other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.ContentType == other.ContentType ||
                    this.ContentType != null &&
                    this.ContentType.Equals(other.ContentType)
                ) && 
                (
                    this.Content == other.Content ||
                    this.Content != null &&
                    this.Content.Equals(other.Content)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.ContentType != null)
                    hash = hash * 59 + this.ContentType.GetHashCode();
                if (this.Content != null)
                    hash = hash * 59 + this.Content.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
