/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using CyberSource.Utilities.Extensibility;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CyberSource.Client.SwaggerDateConverter;

namespace CyberSource.Model
{
    /// <summary>
    /// InlineResponse2014
    /// </summary>
    [DataContract]
    public partial class InlineResponse2014 :  ModelExtensions, IEquatable<InlineResponse2014>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2014" /> class.
        /// </summary>
        /// <param name="Id">A unique identification number to identify the submitted request. It is also appended to the endpoint of the resource. .</param>
        /// <param name="Status">The status of the submitted transaction.  Possible values: - &#x60;COMPLETED&#x60; - &#x60;INVALID_REQUEST&#x60; - &#x60;SERVER_ERROR&#x60; .</param>
        /// <param name="SubmitTimeStampUtc">Time of request in UTC. Format: &#x60;YYYY-MM-DD&#39;T&#39;HH:mm:ssZ&#x60;  Example: &#x60;2016-08-11T22:47:57Z&#x60; equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The T separates the date and the time. The Z indicates UTC. .</param>
        /// <param name="OrderInformation">OrderInformation.</param>
        /// <param name="ErrorInformation">ErrorInformation.</param>
        /// <param name="ProcessorInformation">ProcessorInformation.</param>
        /// <param name="ProcessingInformation">ProcessingInformation.</param>
        public InlineResponse2014(string Id = default(string), string Status = default(string), string SubmitTimeStampUtc = default(string), InlineResponse2014OrderInformation OrderInformation = default(InlineResponse2014OrderInformation), InlineResponse2014ErrorInformation ErrorInformation = default(InlineResponse2014ErrorInformation), InlineResponse2014ProcessorInformation ProcessorInformation = default(InlineResponse2014ProcessorInformation), InlineResponse2014ProcessingInformation ProcessingInformation = default(InlineResponse2014ProcessingInformation))
        {
            this.Id = Id;
            this.Status = Status;
            this.SubmitTimeStampUtc = SubmitTimeStampUtc;
            this.OrderInformation = OrderInformation;
            this.ErrorInformation = ErrorInformation;
            this.ProcessorInformation = ProcessorInformation;
            this.ProcessingInformation = ProcessingInformation;
        }
        
        /// <summary>
        /// A unique identification number to identify the submitted request. It is also appended to the endpoint of the resource. 
        /// </summary>
        /// <value>A unique identification number to identify the submitted request. It is also appended to the endpoint of the resource. </value>
        [JsonPropertyName("id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Id { get; set; }

        /// <summary>
        /// The status of the submitted transaction.  Possible values: - &#x60;COMPLETED&#x60; - &#x60;INVALID_REQUEST&#x60; - &#x60;SERVER_ERROR&#x60; 
        /// </summary>
        /// <value>The status of the submitted transaction.  Possible values: - &#x60;COMPLETED&#x60; - &#x60;INVALID_REQUEST&#x60; - &#x60;SERVER_ERROR&#x60; </value>
        [JsonPropertyName("status")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Status { get; set; }

        /// <summary>
        /// Time of request in UTC. Format: &#x60;YYYY-MM-DD&#39;T&#39;HH:mm:ssZ&#x60;  Example: &#x60;2016-08-11T22:47:57Z&#x60; equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The T separates the date and the time. The Z indicates UTC. 
        /// </summary>
        /// <value>Time of request in UTC. Format: &#x60;YYYY-MM-DD&#39;T&#39;HH:mm:ssZ&#x60;  Example: &#x60;2016-08-11T22:47:57Z&#x60; equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The T separates the date and the time. The Z indicates UTC. </value>
        [JsonPropertyName("submitTimeStampUtc")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SubmitTimeStampUtc { get; set; }

        /// <summary>
        /// Gets or Sets OrderInformation
        /// </summary>
        [JsonPropertyName("orderInformation")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public InlineResponse2014OrderInformation OrderInformation { get; set; }

        /// <summary>
        /// Gets or Sets ErrorInformation
        /// </summary>
        [JsonPropertyName("errorInformation")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public InlineResponse2014ErrorInformation ErrorInformation { get; set; }

        /// <summary>
        /// Gets or Sets ProcessorInformation
        /// </summary>
        [JsonPropertyName("processorInformation")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public InlineResponse2014ProcessorInformation ProcessorInformation { get; set; }

        /// <summary>
        /// Gets or Sets ProcessingInformation
        /// </summary>
        [JsonPropertyName("processingInformation")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public InlineResponse2014ProcessingInformation ProcessingInformation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2014 {\n");
            if (Id != null) sb.Append("  Id: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("InlineResponse2014", "id", Id.ToString())).Append("\n");
            if (Status != null) sb.Append("  Status: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("InlineResponse2014", "status", Status.ToString())).Append("\n");
            if (SubmitTimeStampUtc != null) sb.Append("  SubmitTimeStampUtc: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("InlineResponse2014", "submitTimeStampUtc", SubmitTimeStampUtc.ToString())).Append("\n");
            if (OrderInformation != null) sb.Append("  OrderInformation: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("InlineResponse2014", "orderInformation", OrderInformation.ToString())).Append("\n");
            if (ErrorInformation != null) sb.Append("  ErrorInformation: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("InlineResponse2014", "errorInformation", ErrorInformation.ToString())).Append("\n");
            if (ProcessorInformation != null) sb.Append("  ProcessorInformation: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("InlineResponse2014", "processorInformation", ProcessorInformation.ToString())).Append("\n");
            if (ProcessingInformation != null) sb.Append("  ProcessingInformation: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("InlineResponse2014", "processingInformation", ProcessingInformation.ToString())).Append("\n");
            sb.Append(ToStringExtraFields());
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Utilities.SensitiveFieldMaskingUtility.MaskSensitiveDataInJson("InlineResponse2014", JsonSerializer.Serialize(this, EffectiveSerializerOptions));
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InlineResponse2014);
        }

        /// <summary>
        /// Returns true if InlineResponse2014 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse2014 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2014 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            // Value-based equality over the typed (declared) properties AND the hidden
            // overflow store ([JsonExtensionData]) (design G5). Extra fields are compared by
            // semantic JSON value-equality (JsonElement has no built-in value equality).
            // ExtraFieldsEqual leads so models with no declared properties still compare.
            return ExtraFieldsEqual(other) && 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.SubmitTimeStampUtc == other.SubmitTimeStampUtc ||
                    this.SubmitTimeStampUtc != null &&
                    this.SubmitTimeStampUtc.Equals(other.SubmitTimeStampUtc)
                ) && 
                (
                    this.OrderInformation == other.OrderInformation ||
                    this.OrderInformation != null &&
                    this.OrderInformation.Equals(other.OrderInformation)
                ) && 
                (
                    this.ErrorInformation == other.ErrorInformation ||
                    this.ErrorInformation != null &&
                    this.ErrorInformation.Equals(other.ErrorInformation)
                ) && 
                (
                    this.ProcessorInformation == other.ProcessorInformation ||
                    this.ProcessorInformation != null &&
                    this.ProcessorInformation.Equals(other.ProcessorInformation)
                ) && 
                (
                    this.ProcessingInformation == other.ProcessingInformation ||
                    this.ProcessingInformation != null &&
                    this.ProcessingInformation.Equals(other.ProcessingInformation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                // Value-based hash over declared properties AND the overflow store, kept
                // consistent with Equals.
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.SubmitTimeStampUtc != null)
                    hash = hash * 59 + this.SubmitTimeStampUtc.GetHashCode();
                if (this.OrderInformation != null)
                    hash = hash * 59 + this.OrderInformation.GetHashCode();
                if (this.ErrorInformation != null)
                    hash = hash * 59 + this.ErrorInformation.GetHashCode();
                if (this.ProcessorInformation != null)
                    hash = hash * 59 + this.ProcessorInformation.GetHashCode();
                if (this.ProcessingInformation != null)
                    hash = hash * 59 + this.ProcessingInformation.GetHashCode();
                hash = hash * 59 + GetExtraFieldsHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
