/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using CyberSource.Utilities.Extensibility;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CyberSource.Client.SwaggerDateConverter;

namespace CyberSource.Model
{
    /// <summary>
    /// Label submission request for providing ground truth feedback on previously assessed transactions
    /// </summary>
    [DataContract]
    public partial class LabelRequest :  ModelExtensions, IEquatable<LabelRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LabelRequest" /> class.
        /// </summary>
        [JsonConstructor]
        protected LabelRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LabelRequest" /> class.
        /// </summary>
        /// <param name="Actions">Actions to perform. For label submission, specify VISA_PROTECT_RISK_INSIGHTS. (required).</param>
        /// <param name="Events">Must be LABELS for label submission requests. (required).</param>
        /// <param name="RequestId">Unique identifier for the label submission request.</param>
        /// <param name="EventTime">The time that the real-world event occurred..</param>
        /// <param name="Transaction">Transaction (required).</param>
        /// <param name="Labels">Labels (required).</param>
        public LabelRequest(List<string> Actions = default(List<string>), List<string> Events = default(List<string>), string RequestId = default(string), DateTime? EventTime = default(DateTime?), UnifiedriskTransaction Transaction = default(UnifiedriskTransaction), UnifiedriskLabels Labels = default(UnifiedriskLabels))
        {
            this.Actions = Actions;
            this.Events = Events;
            this.RequestId = RequestId;
            this.EventTime = EventTime;
            this.Transaction = Transaction;
            this.Labels = Labels;
        }
        
        /// <summary>
        /// Actions to perform. For label submission, specify VISA_PROTECT_RISK_INSIGHTS.
        /// </summary>
        /// <value>Actions to perform. For label submission, specify VISA_PROTECT_RISK_INSIGHTS.</value>
        [JsonPropertyName("actions")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<string> Actions { get; set; }

        /// <summary>
        /// Must be LABELS for label submission requests.
        /// </summary>
        /// <value>Must be LABELS for label submission requests.</value>
        [JsonPropertyName("events")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<string> Events { get; set; }

        /// <summary>
        /// Unique identifier for the label submission request
        /// </summary>
        /// <value>Unique identifier for the label submission request</value>
        [JsonPropertyName("requestId")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string RequestId { get; set; }

        /// <summary>
        /// The time that the real-world event occurred.
        /// </summary>
        /// <value>The time that the real-world event occurred.</value>
        [JsonPropertyName("eventTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? EventTime { get; set; }

        /// <summary>
        /// Gets or Sets Transaction
        /// </summary>
        [JsonPropertyName("transaction")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public UnifiedriskTransaction Transaction { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [JsonPropertyName("labels")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public UnifiedriskLabels Labels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LabelRequest {\n");
            if (Actions != null) sb.Append("  Actions: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("LabelRequest", "actions", Actions.ToString())).Append("\n");
            if (Events != null) sb.Append("  Events: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("LabelRequest", "events", Events.ToString())).Append("\n");
            if (RequestId != null) sb.Append("  RequestId: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("LabelRequest", "requestId", RequestId.ToString())).Append("\n");
            if (EventTime != null) sb.Append("  EventTime: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("LabelRequest", "eventTime", EventTime.ToString())).Append("\n");
            if (Transaction != null) sb.Append("  Transaction: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("LabelRequest", "transaction", Transaction.ToString())).Append("\n");
            if (Labels != null) sb.Append("  Labels: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("LabelRequest", "labels", Labels.ToString())).Append("\n");
            sb.Append(ToStringExtraFields());
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Utilities.SensitiveFieldMaskingUtility.MaskSensitiveDataInJson("LabelRequest", JsonSerializer.Serialize(this, EffectiveSerializerOptions));
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as LabelRequest);
        }

        /// <summary>
        /// Returns true if LabelRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of LabelRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LabelRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            // Value-based equality over the typed (declared) properties AND the hidden
            // overflow store ([JsonExtensionData]) (design G5). Extra fields are compared by
            // semantic JSON value-equality (JsonElement has no built-in value equality).
            // ExtraFieldsEqual leads so models with no declared properties still compare.
            return ExtraFieldsEqual(other) && 
                (
                    this.Actions == other.Actions ||
                    this.Actions != null &&
                    this.Actions.SequenceEqual(other.Actions)
                ) && 
                (
                    this.Events == other.Events ||
                    this.Events != null &&
                    this.Events.SequenceEqual(other.Events)
                ) && 
                (
                    this.RequestId == other.RequestId ||
                    this.RequestId != null &&
                    this.RequestId.Equals(other.RequestId)
                ) && 
                (
                    this.EventTime == other.EventTime ||
                    this.EventTime != null &&
                    this.EventTime.Equals(other.EventTime)
                ) && 
                (
                    this.Transaction == other.Transaction ||
                    this.Transaction != null &&
                    this.Transaction.Equals(other.Transaction)
                ) && 
                (
                    this.Labels == other.Labels ||
                    this.Labels != null &&
                    this.Labels.Equals(other.Labels)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                // Value-based hash over declared properties AND the overflow store, kept
                // consistent with Equals.
                if (this.Actions != null)
                    hash = hash * 59 + this.Actions.GetHashCode();
                if (this.Events != null)
                    hash = hash * 59 + this.Events.GetHashCode();
                if (this.RequestId != null)
                    hash = hash * 59 + this.RequestId.GetHashCode();
                if (this.EventTime != null)
                    hash = hash * 59 + this.EventTime.GetHashCode();
                if (this.Transaction != null)
                    hash = hash * 59 + this.Transaction.GetHashCode();
                if (this.Labels != null)
                    hash = hash * 59 + this.Labels.GetHashCode();
                hash = hash * 59 + GetExtraFieldsHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
