/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using CyberSource.Utilities.Extensibility;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CyberSource.Client.SwaggerDateConverter;

namespace CyberSource.Model
{
    /// <summary>
    /// Contains link specific detail.
    /// </summary>
    [DataContract]
    public partial class PblPaymentLinksAllGet200ResponsePurchaseInformation :  ModelExtensions, IEquatable<PblPaymentLinksAllGet200ResponsePurchaseInformation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PblPaymentLinksAllGet200ResponsePurchaseInformation" /> class.
        /// </summary>
        /// <param name="PurchaseNumber">The purchase number.</param>
        /// <param name="PaymentLink">Returns the link to a purchase or donation link when the status is &#x60;ACTIVE&#x60;..</param>
        public PblPaymentLinksAllGet200ResponsePurchaseInformation(string PurchaseNumber = default(string), string PaymentLink = default(string))
        {
            this.PurchaseNumber = PurchaseNumber;
            this.PaymentLink = PaymentLink;
        }
        
        /// <summary>
        /// The purchase number
        /// </summary>
        /// <value>The purchase number</value>
        [JsonPropertyName("purchaseNumber")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string PurchaseNumber { get; set; }

        /// <summary>
        /// Returns the link to a purchase or donation link when the status is &#x60;ACTIVE&#x60;.
        /// </summary>
        /// <value>Returns the link to a purchase or donation link when the status is &#x60;ACTIVE&#x60;.</value>
        [JsonPropertyName("paymentLink")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string PaymentLink { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PblPaymentLinksAllGet200ResponsePurchaseInformation {\n");
            if (PurchaseNumber != null) sb.Append("  PurchaseNumber: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("PblPaymentLinksAllGet200ResponsePurchaseInformation", "purchaseNumber", PurchaseNumber.ToString())).Append("\n");
            if (PaymentLink != null) sb.Append("  PaymentLink: ").Append(CyberSource.Utilities.SensitiveFieldMaskingUtility.MaskFieldValue("PblPaymentLinksAllGet200ResponsePurchaseInformation", "paymentLink", PaymentLink.ToString())).Append("\n");
            sb.Append(ToStringExtraFields());
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Utilities.SensitiveFieldMaskingUtility.MaskSensitiveDataInJson("PblPaymentLinksAllGet200ResponsePurchaseInformation", JsonSerializer.Serialize(this, EffectiveSerializerOptions));
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as PblPaymentLinksAllGet200ResponsePurchaseInformation);
        }

        /// <summary>
        /// Returns true if PblPaymentLinksAllGet200ResponsePurchaseInformation instances are equal
        /// </summary>
        /// <param name="other">Instance of PblPaymentLinksAllGet200ResponsePurchaseInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PblPaymentLinksAllGet200ResponsePurchaseInformation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            // Value-based equality over the typed (declared) properties AND the hidden
            // overflow store ([JsonExtensionData]) (design G5). Extra fields are compared by
            // semantic JSON value-equality (JsonElement has no built-in value equality).
            // ExtraFieldsEqual leads so models with no declared properties still compare.
            return ExtraFieldsEqual(other) && 
                (
                    this.PurchaseNumber == other.PurchaseNumber ||
                    this.PurchaseNumber != null &&
                    this.PurchaseNumber.Equals(other.PurchaseNumber)
                ) && 
                (
                    this.PaymentLink == other.PaymentLink ||
                    this.PaymentLink != null &&
                    this.PaymentLink.Equals(other.PaymentLink)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                // Value-based hash over declared properties AND the overflow store, kept
                // consistent with Equals.
                if (this.PurchaseNumber != null)
                    hash = hash * 59 + this.PurchaseNumber.GetHashCode();
                if (this.PaymentLink != null)
                    hash = hash * 59 + this.PaymentLink.GetHashCode();
                hash = hash * 59 + GetExtraFieldsHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
