/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing InvoicingV2InvoicesPost201ResponseOrderInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvoicingV2InvoicesPost201ResponseOrderInformationTests
    {
        // TODO uncomment below to declare an instance variable for InvoicingV2InvoicesPost201ResponseOrderInformation
        //private InvoicingV2InvoicesPost201ResponseOrderInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvoicingV2InvoicesPost201ResponseOrderInformation
            //instance = new InvoicingV2InvoicesPost201ResponseOrderInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvoicingV2InvoicesPost201ResponseOrderInformation
        /// </summary>
        [Test]
        public void InvoicingV2InvoicesPost201ResponseOrderInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InvoicingV2InvoicesPost201ResponseOrderInformation
            //Assert.IsInstanceOfType<InvoicingV2InvoicesPost201ResponseOrderInformation> (instance, "variable 'instance' is a InvoicingV2InvoicesPost201ResponseOrderInformation");
        }

        /// <summary>
        /// Test the property 'AmountDetails'
        /// </summary>
        [Test]
        public void AmountDetailsTest()
        {
            // TODO unit test for the property 'AmountDetails'
        }
        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Test]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }

    }

}
