/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing PtsV2PaymentsPost201ResponseLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PtsV2PaymentsPost201ResponseLinksTests
    {
        // TODO uncomment below to declare an instance variable for PtsV2PaymentsPost201ResponseLinks
        //private PtsV2PaymentsPost201ResponseLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PtsV2PaymentsPost201ResponseLinks
            //instance = new PtsV2PaymentsPost201ResponseLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PtsV2PaymentsPost201ResponseLinks
        /// </summary>
        [Test]
        public void PtsV2PaymentsPost201ResponseLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PtsV2PaymentsPost201ResponseLinks
            //Assert.IsInstanceOfType<PtsV2PaymentsPost201ResponseLinks> (instance, "variable 'instance' is a PtsV2PaymentsPost201ResponseLinks");
        }

        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Test]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }
        /// <summary>
        /// Test the property 'Reversal'
        /// </summary>
        [Test]
        public void ReversalTest()
        {
            // TODO unit test for the property 'Reversal'
        }
        /// <summary>
        /// Test the property 'Capture'
        /// </summary>
        [Test]
        public void CaptureTest()
        {
            // TODO unit test for the property 'Capture'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Test]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'PaymentInstrument'
        /// </summary>
        [Test]
        public void PaymentInstrumentTest()
        {
            // TODO unit test for the property 'PaymentInstrument'
        }
        /// <summary>
        /// Test the property 'ShippingAddress'
        /// </summary>
        [Test]
        public void ShippingAddressTest()
        {
            // TODO unit test for the property 'ShippingAddress'
        }
        /// <summary>
        /// Test the property 'InstrumentIdentifier'
        /// </summary>
        [Test]
        public void InstrumentIdentifierTest()
        {
            // TODO unit test for the property 'InstrumentIdentifier'
        }

    }

}
