/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAssetTests
    {
        // TODO uncomment below to declare an instance variable for TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset
        //private TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset
            //instance = new TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset
        /// </summary>
        [Test]
        public void TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAssetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset
            //Assert.IsInstanceOfType<TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset> (instance, "variable 'instance' is a TmsIssuerLifeCycleEventSimulationMetadataCardArtCombinedAsset");
        }

        /// <summary>
        /// Test the property 'Update'
        /// </summary>
        [Test]
        public void UpdateTest()
        {
            // TODO unit test for the property 'Update'
        }

    }

}
