/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing UmsV1UsersGet200ResponseAccountInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UmsV1UsersGet200ResponseAccountInformationTests
    {
        // TODO uncomment below to declare an instance variable for UmsV1UsersGet200ResponseAccountInformation
        //private UmsV1UsersGet200ResponseAccountInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UmsV1UsersGet200ResponseAccountInformation
            //instance = new UmsV1UsersGet200ResponseAccountInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UmsV1UsersGet200ResponseAccountInformation
        /// </summary>
        [Test]
        public void UmsV1UsersGet200ResponseAccountInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UmsV1UsersGet200ResponseAccountInformation
            //Assert.IsInstanceOfType<UmsV1UsersGet200ResponseAccountInformation> (instance, "variable 'instance' is a UmsV1UsersGet200ResponseAccountInformation");
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'RoleId'
        /// </summary>
        [Test]
        public void RoleIdTest()
        {
            // TODO unit test for the property 'RoleId'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Test]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Test]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }
        /// <summary>
        /// Test the property 'LastAccessTime'
        /// </summary>
        [Test]
        public void LastAccessTimeTest()
        {
            // TODO unit test for the property 'LastAccessTime'
        }
        /// <summary>
        /// Test the property 'LanguagePreference'
        /// </summary>
        [Test]
        public void LanguagePreferenceTest()
        {
            // TODO unit test for the property 'LanguagePreference'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

    }

}
