/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing VpriRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VpriRequestTests
    {
        // TODO uncomment below to declare an instance variable for VpriRequest
        //private VpriRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VpriRequest
            //instance = new VpriRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VpriRequest
        /// </summary>
        [Test]
        public void VpriRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VpriRequest
            //Assert.IsInstanceOfType<VpriRequest> (instance, "variable 'instance' is a VpriRequest");
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Test]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Test]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Test]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }
        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'EventTime'
        /// </summary>
        [Test]
        public void EventTimeTest()
        {
            // TODO unit test for the property 'EventTime'
        }
        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'RequestComments'
        /// </summary>
        [Test]
        public void RequestCommentsTest()
        {
            // TODO unit test for the property 'RequestComments'
        }
        /// <summary>
        /// Test the property 'SchemaVersion'
        /// </summary>
        [Test]
        public void SchemaVersionTest()
        {
            // TODO unit test for the property 'SchemaVersion'
        }
        /// <summary>
        /// Test the property 'Partner'
        /// </summary>
        [Test]
        public void PartnerTest()
        {
            // TODO unit test for the property 'Partner'
        }
        /// <summary>
        /// Test the property 'Payment'
        /// </summary>
        [Test]
        public void PaymentTest()
        {
            // TODO unit test for the property 'Payment'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Test]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'RiskAssessment'
        /// </summary>
        [Test]
        public void RiskAssessmentTest()
        {
            // TODO unit test for the property 'RiskAssessment'
        }
        /// <summary>
        /// Test the property 'Travel'
        /// </summary>
        [Test]
        public void TravelTest()
        {
            // TODO unit test for the property 'Travel'
        }
        /// <summary>
        /// Test the property 'Merchant'
        /// </summary>
        [Test]
        public void MerchantTest()
        {
            // TODO unit test for the property 'Merchant'
        }
        /// <summary>
        /// Test the property 'Acquirer'
        /// </summary>
        [Test]
        public void AcquirerTest()
        {
            // TODO unit test for the property 'Acquirer'
        }
        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Test]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Test]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }
        /// <summary>
        /// Test the property 'SupplementaryData'
        /// </summary>
        [Test]
        public void SupplementaryDataTest()
        {
            // TODO unit test for the property 'SupplementaryData'
        }
        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Test]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Authentication'
        /// </summary>
        [Test]
        public void AuthenticationTest()
        {
            // TODO unit test for the property 'Authentication'
        }
        /// <summary>
        /// Test the property 'Authorization'
        /// </summary>
        [Test]
        public void AuthorizationTest()
        {
            // TODO unit test for the property 'Authorization'
        }
        /// <summary>
        /// Test the property 'Browser'
        /// </summary>
        [Test]
        public void BrowserTest()
        {
            // TODO unit test for the property 'Browser'
        }
        /// <summary>
        /// Test the property 'InitiatingParty'
        /// </summary>
        [Test]
        public void InitiatingPartyTest()
        {
            // TODO unit test for the property 'InitiatingParty'
        }
        /// <summary>
        /// Test the property 'Terminal'
        /// </summary>
        [Test]
        public void TerminalTest()
        {
            // TODO unit test for the property 'Terminal'
        }
        /// <summary>
        /// Test the property 'ThirdPartyRisk'
        /// </summary>
        [Test]
        public void ThirdPartyRiskTest()
        {
            // TODO unit test for the property 'ThirdPartyRisk'
        }

    }

}
