/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Acpv1instructionsinstructionIdcredentialsOrderInformationLineItemsTests
    {
        // TODO uncomment below to declare an instance variable for Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems
        //private Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems
            //instance = new Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems
        /// </summary>
        [Test]
        public void Acpv1instructionsinstructionIdcredentialsOrderInformationLineItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems
            //Assert.IsInstanceOfType<Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems> (instance, "variable 'instance' is a Acpv1instructionsinstructionIdcredentialsOrderInformationLineItems");
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
