/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2005EmbeddedLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2005EmbeddedLinksTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2005EmbeddedLinks
        //private InlineResponse2005EmbeddedLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2005EmbeddedLinks
            //instance = new InlineResponse2005EmbeddedLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2005EmbeddedLinks
        /// </summary>
        [Test]
        public void InlineResponse2005EmbeddedLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2005EmbeddedLinks
            //Assert.IsInstanceOfType<InlineResponse2005EmbeddedLinks> (instance, "variable 'instance' is a InlineResponse2005EmbeddedLinks");
        }

        /// <summary>
        /// Test the property 'Reports'
        /// </summary>
        [Test]
        public void ReportsTest()
        {
            // TODO unit test for the property 'Reports'
        }

    }

}
