/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing InlineResponse200PlanInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse200PlanInformationTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse200PlanInformation
        //private InlineResponse200PlanInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse200PlanInformation
            //instance = new InlineResponse200PlanInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse200PlanInformation
        /// </summary>
        [Test]
        public void InlineResponse200PlanInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse200PlanInformation
            //Assert.IsInstanceOfType<InlineResponse200PlanInformation> (instance, "variable 'instance' is a InlineResponse200PlanInformation");
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'BillingPeriod'
        /// </summary>
        [Test]
        public void BillingPeriodTest()
        {
            // TODO unit test for the property 'BillingPeriod'
        }
        /// <summary>
        /// Test the property 'BillingCycles'
        /// </summary>
        [Test]
        public void BillingCyclesTest()
        {
            // TODO unit test for the property 'BillingCycles'
        }

    }

}
