/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2003EmbeddedReversal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2003EmbeddedReversalTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2003EmbeddedReversal
        //private InlineResponse2003EmbeddedReversal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2003EmbeddedReversal
            //instance = new InlineResponse2003EmbeddedReversal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2003EmbeddedReversal
        /// </summary>
        [Test]
        public void InlineResponse2003EmbeddedReversalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2003EmbeddedReversal
            //Assert.IsInstanceOfType<InlineResponse2003EmbeddedReversal> (instance, "variable 'instance' is a InlineResponse2003EmbeddedReversal");
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
