/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing Invoicingv2invoicesOrderInformationAmountDetailsFreight
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Invoicingv2invoicesOrderInformationAmountDetailsFreightTests
    {
        // TODO uncomment below to declare an instance variable for Invoicingv2invoicesOrderInformationAmountDetailsFreight
        //private Invoicingv2invoicesOrderInformationAmountDetailsFreight instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Invoicingv2invoicesOrderInformationAmountDetailsFreight
            //instance = new Invoicingv2invoicesOrderInformationAmountDetailsFreight();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Invoicingv2invoicesOrderInformationAmountDetailsFreight
        /// </summary>
        [Test]
        public void Invoicingv2invoicesOrderInformationAmountDetailsFreightInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Invoicingv2invoicesOrderInformationAmountDetailsFreight
            //Assert.IsInstanceOfType<Invoicingv2invoicesOrderInformationAmountDetailsFreight> (instance, "variable 'instance' is a Invoicingv2invoicesOrderInformationAmountDetailsFreight");
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Taxable'
        /// </summary>
        [Test]
        public void TaxableTest()
        {
            // TODO unit test for the property 'Taxable'
        }

    }

}
