/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing Notificationsubscriptionsv1webhooksSecurityPolicyConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Notificationsubscriptionsv1webhooksSecurityPolicyConfigTests
    {
        // TODO uncomment below to declare an instance variable for Notificationsubscriptionsv1webhooksSecurityPolicyConfig
        //private Notificationsubscriptionsv1webhooksSecurityPolicyConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Notificationsubscriptionsv1webhooksSecurityPolicyConfig
            //instance = new Notificationsubscriptionsv1webhooksSecurityPolicyConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Notificationsubscriptionsv1webhooksSecurityPolicyConfig
        /// </summary>
        [Test]
        public void Notificationsubscriptionsv1webhooksSecurityPolicyConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Notificationsubscriptionsv1webhooksSecurityPolicyConfig
            //Assert.IsInstanceOfType<Notificationsubscriptionsv1webhooksSecurityPolicyConfig> (instance, "variable 'instance' is a Notificationsubscriptionsv1webhooksSecurityPolicyConfig");
        }

        /// <summary>
        /// Test the property 'OAuthTokenExpiry'
        /// </summary>
        [Test]
        public void OAuthTokenExpiryTest()
        {
            // TODO unit test for the property 'OAuthTokenExpiry'
        }
        /// <summary>
        /// Test the property 'OAuthURL'
        /// </summary>
        [Test]
        public void OAuthURLTest()
        {
            // TODO unit test for the property 'OAuthURL'
        }
        /// <summary>
        /// Test the property 'OAuthTokenType'
        /// </summary>
        [Test]
        public void OAuthTokenTypeTest()
        {
            // TODO unit test for the property 'OAuthTokenType'
        }

    }

}
