/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing PaymentInstrumentListLinksSelf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentInstrumentListLinksSelfTests
    {
        // TODO uncomment below to declare an instance variable for PaymentInstrumentListLinksSelf
        //private PaymentInstrumentListLinksSelf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentInstrumentListLinksSelf
            //instance = new PaymentInstrumentListLinksSelf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentInstrumentListLinksSelf
        /// </summary>
        [Test]
        public void PaymentInstrumentListLinksSelfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentInstrumentListLinksSelf
            //Assert.IsInstanceOfType<PaymentInstrumentListLinksSelf> (instance, "variable 'instance' is a PaymentInstrumentListLinksSelf");
        }

        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
