/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing Ptsv2payoutsProcessingInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Ptsv2payoutsProcessingInformationTests
    {
        // TODO uncomment below to declare an instance variable for Ptsv2payoutsProcessingInformation
        //private Ptsv2payoutsProcessingInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Ptsv2payoutsProcessingInformation
            //instance = new Ptsv2payoutsProcessingInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Ptsv2payoutsProcessingInformation
        /// </summary>
        [Test]
        public void Ptsv2payoutsProcessingInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Ptsv2payoutsProcessingInformation
            //Assert.IsInstanceOfType<Ptsv2payoutsProcessingInformation> (instance, "variable 'instance' is a Ptsv2payoutsProcessingInformation");
        }

        /// <summary>
        /// Test the property 'BusinessApplicationId'
        /// </summary>
        [Test]
        public void BusinessApplicationIdTest()
        {
            // TODO unit test for the property 'BusinessApplicationId'
        }
        /// <summary>
        /// Test the property 'NetworkRoutingOrder'
        /// </summary>
        [Test]
        public void NetworkRoutingOrderTest()
        {
            // TODO unit test for the property 'NetworkRoutingOrder'
        }
        /// <summary>
        /// Test the property 'CommerceIndicator'
        /// </summary>
        [Test]
        public void CommerceIndicatorTest()
        {
            // TODO unit test for the property 'CommerceIndicator'
        }
        /// <summary>
        /// Test the property 'ReconciliationId'
        /// </summary>
        [Test]
        public void ReconciliationIdTest()
        {
            // TODO unit test for the property 'ReconciliationId'
        }
        /// <summary>
        /// Test the property 'PayoutsOptions'
        /// </summary>
        [Test]
        public void PayoutsOptionsTest()
        {
            // TODO unit test for the property 'PayoutsOptions'
        }
        /// <summary>
        /// Test the property 'TransactionReason'
        /// </summary>
        [Test]
        public void TransactionReasonTest()
        {
            // TODO unit test for the property 'TransactionReason'
        }
        /// <summary>
        /// Test the property 'PurposeOfPayment'
        /// </summary>
        [Test]
        public void PurposeOfPaymentTest()
        {
            // TODO unit test for the property 'PurposeOfPayment'
        }
        /// <summary>
        /// Test the property 'FundingOptions'
        /// </summary>
        [Test]
        public void FundingOptionsTest()
        {
            // TODO unit test for the property 'FundingOptions'
        }

    }

}
