/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing ReportingV3ReportDefinitionsNameGet200ResponseAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportingV3ReportDefinitionsNameGet200ResponseAttributesTests
    {
        // TODO uncomment below to declare an instance variable for ReportingV3ReportDefinitionsNameGet200ResponseAttributes
        //private ReportingV3ReportDefinitionsNameGet200ResponseAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportingV3ReportDefinitionsNameGet200ResponseAttributes
            //instance = new ReportingV3ReportDefinitionsNameGet200ResponseAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportingV3ReportDefinitionsNameGet200ResponseAttributes
        /// </summary>
        [Test]
        public void ReportingV3ReportDefinitionsNameGet200ResponseAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportingV3ReportDefinitionsNameGet200ResponseAttributes
            //Assert.IsInstanceOfType<ReportingV3ReportDefinitionsNameGet200ResponseAttributes> (instance, "variable 'instance' is a ReportingV3ReportDefinitionsNameGet200ResponseAttributes");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FilterType'
        /// </summary>
        [Test]
        public void FilterTypeTest()
        {
            // TODO unit test for the property 'FilterType'
        }
        /// <summary>
        /// Test the property '_Default'
        /// </summary>
        [Test]
        public void _DefaultTest()
        {
            // TODO unit test for the property '_Default'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'SupportedType'
        /// </summary>
        [Test]
        public void SupportedTypeTest()
        {
            // TODO unit test for the property 'SupportedType'
        }

    }

}
