/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing ReportingV3PurchaseRefundDetailsGet200ResponseSettlements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportingV3PurchaseRefundDetailsGet200ResponseSettlementsTests
    {
        // TODO uncomment below to declare an instance variable for ReportingV3PurchaseRefundDetailsGet200ResponseSettlements
        //private ReportingV3PurchaseRefundDetailsGet200ResponseSettlements instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportingV3PurchaseRefundDetailsGet200ResponseSettlements
            //instance = new ReportingV3PurchaseRefundDetailsGet200ResponseSettlements();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportingV3PurchaseRefundDetailsGet200ResponseSettlements
        /// </summary>
        [Test]
        public void ReportingV3PurchaseRefundDetailsGet200ResponseSettlementsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportingV3PurchaseRefundDetailsGet200ResponseSettlements
            //Assert.IsInstanceOfType<ReportingV3PurchaseRefundDetailsGet200ResponseSettlements> (instance, "variable 'instance' is a ReportingV3PurchaseRefundDetailsGet200ResponseSettlements");
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'TransactionType'
        /// </summary>
        [Test]
        public void TransactionTypeTest()
        {
            // TODO unit test for the property 'TransactionType'
        }
        /// <summary>
        /// Test the property 'SubmissionTime'
        /// </summary>
        [Test]
        public void SubmissionTimeTest()
        {
            // TODO unit test for the property 'SubmissionTime'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'WalletType'
        /// </summary>
        [Test]
        public void WalletTypeTest()
        {
            // TODO unit test for the property 'WalletType'
        }
        /// <summary>
        /// Test the property 'PaymentType'
        /// </summary>
        [Test]
        public void PaymentTypeTest()
        {
            // TODO unit test for the property 'PaymentType'
        }
        /// <summary>
        /// Test the property 'AccountSuffix'
        /// </summary>
        [Test]
        public void AccountSuffixTest()
        {
            // TODO unit test for the property 'AccountSuffix'
        }
        /// <summary>
        /// Test the property 'CybersourceBatchTime'
        /// </summary>
        [Test]
        public void CybersourceBatchTimeTest()
        {
            // TODO unit test for the property 'CybersourceBatchTime'
        }
        /// <summary>
        /// Test the property 'CybersourceBatchId'
        /// </summary>
        [Test]
        public void CybersourceBatchIdTest()
        {
            // TODO unit test for the property 'CybersourceBatchId'
        }
        /// <summary>
        /// Test the property 'CardType'
        /// </summary>
        [Test]
        public void CardTypeTest()
        {
            // TODO unit test for the property 'CardType'
        }
        /// <summary>
        /// Test the property 'DebitNetwork'
        /// </summary>
        [Test]
        public void DebitNetworkTest()
        {
            // TODO unit test for the property 'DebitNetwork'
        }

    }

}
