/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing RiskProductsDecisionManagerConfigurationInformationConfigurations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RiskProductsDecisionManagerConfigurationInformationConfigurationsTests
    {
        // TODO uncomment below to declare an instance variable for RiskProductsDecisionManagerConfigurationInformationConfigurations
        //private RiskProductsDecisionManagerConfigurationInformationConfigurations instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RiskProductsDecisionManagerConfigurationInformationConfigurations
            //instance = new RiskProductsDecisionManagerConfigurationInformationConfigurations();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RiskProductsDecisionManagerConfigurationInformationConfigurations
        /// </summary>
        [Test]
        public void RiskProductsDecisionManagerConfigurationInformationConfigurationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RiskProductsDecisionManagerConfigurationInformationConfigurations
            //Assert.IsInstanceOfType<RiskProductsDecisionManagerConfigurationInformationConfigurations> (instance, "variable 'instance' is a RiskProductsDecisionManagerConfigurationInformationConfigurations");
        }

        /// <summary>
        /// Test the property 'ProcessingOptions'
        /// </summary>
        [Test]
        public void ProcessingOptionsTest()
        {
            // TODO unit test for the property 'ProcessingOptions'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Test]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'PortfolioControls'
        /// </summary>
        [Test]
        public void PortfolioControlsTest()
        {
            // TODO unit test for the property 'PortfolioControls'
        }
        /// <summary>
        /// Test the property 'Thirdparty'
        /// </summary>
        [Test]
        public void ThirdpartyTest()
        {
            // TODO unit test for the property 'Thirdparty'
        }

    }

}
