/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing Riskv1authenticationsTravelInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Riskv1authenticationsTravelInformationTests
    {
        // TODO uncomment below to declare an instance variable for Riskv1authenticationsTravelInformation
        //private Riskv1authenticationsTravelInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Riskv1authenticationsTravelInformation
            //instance = new Riskv1authenticationsTravelInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Riskv1authenticationsTravelInformation
        /// </summary>
        [Test]
        public void Riskv1authenticationsTravelInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Riskv1authenticationsTravelInformation
            //Assert.IsInstanceOfType<Riskv1authenticationsTravelInformation> (instance, "variable 'instance' is a Riskv1authenticationsTravelInformation");
        }

        /// <summary>
        /// Test the property 'Legs'
        /// </summary>
        [Test]
        public void LegsTest()
        {
            // TODO unit test for the property 'Legs'
        }
        /// <summary>
        /// Test the property 'NumberOfPassengers'
        /// </summary>
        [Test]
        public void NumberOfPassengersTest()
        {
            // TODO unit test for the property 'NumberOfPassengers'
        }
        /// <summary>
        /// Test the property 'Passengers'
        /// </summary>
        [Test]
        public void PassengersTest()
        {
            // TODO unit test for the property 'Passengers'
        }

    }

}
