/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing Tmsv2customersMerchantDefinedInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Tmsv2customersMerchantDefinedInformationTests
    {
        // TODO uncomment below to declare an instance variable for Tmsv2customersMerchantDefinedInformation
        //private Tmsv2customersMerchantDefinedInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Tmsv2customersMerchantDefinedInformation
            //instance = new Tmsv2customersMerchantDefinedInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Tmsv2customersMerchantDefinedInformation
        /// </summary>
        [Test]
        public void Tmsv2customersMerchantDefinedInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Tmsv2customersMerchantDefinedInformation
            //Assert.IsInstanceOfType<Tmsv2customersMerchantDefinedInformation> (instance, "variable 'instance' is a Tmsv2customersMerchantDefinedInformation");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
