/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethodTests
    {
        // TODO uncomment below to declare an instance variable for TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod
        //private TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod
            //instance = new TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod
        /// </summary>
        [Test]
        public void TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod
            //Assert.IsInstanceOfType<TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod> (instance, "variable 'instance' is a TssV2TransactionsGet200ResponsePaymentInformationPaymentTypeMethod");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_Operator'
        /// </summary>
        [Test]
        public void _OperatorTest()
        {
            // TODO unit test for the property '_Operator'
        }
        /// <summary>
        /// Test the property 'SchemeName'
        /// </summary>
        [Test]
        public void SchemeNameTest()
        {
            // TODO unit test for the property 'SchemeName'
        }
        /// <summary>
        /// Test the property 'SchemeOperator'
        /// </summary>
        [Test]
        public void SchemeOperatorTest()
        {
            // TODO unit test for the property 'SchemeOperator'
        }

    }

}
