/* 
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing Upv1capturecontextsDataProcessingInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Upv1capturecontextsDataProcessingInformationTests
    {
        // TODO uncomment below to declare an instance variable for Upv1capturecontextsDataProcessingInformation
        //private Upv1capturecontextsDataProcessingInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Upv1capturecontextsDataProcessingInformation
            //instance = new Upv1capturecontextsDataProcessingInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Upv1capturecontextsDataProcessingInformation
        /// </summary>
        [Test]
        public void Upv1capturecontextsDataProcessingInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Upv1capturecontextsDataProcessingInformation
            //Assert.IsInstanceOfType<Upv1capturecontextsDataProcessingInformation> (instance, "variable 'instance' is a Upv1capturecontextsDataProcessingInformation");
        }

        /// <summary>
        /// Test the property 'ReconciliationId'
        /// </summary>
        [Test]
        public void ReconciliationIdTest()
        {
            // TODO unit test for the property 'ReconciliationId'
        }
        /// <summary>
        /// Test the property 'AuthorizationOptions'
        /// </summary>
        [Test]
        public void AuthorizationOptionsTest()
        {
            // TODO unit test for the property 'AuthorizationOptions'
        }

    }

}
