name: DOTNET BUILDS
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  CLIENT_FOLDER: 'cybersource-rest-client-dotnet'
  SAMPLE_FOLDER: 'cybersource-rest-samples-csharp'
jobs:
    build-the-dotnet-client:
        defaults:
            run:
              shell: bash
        runs-on: windows-2019
        steps:
            - name: Checkout cybersource-rest-client-dotnet repo
              uses: actions/checkout@v4
              with:
                # ref: 'release-sep24'
                path: ${{env.CLIENT_FOLDER}}
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2
            - name: Building the Dotnet Client
              run: |
                cd $Env:CLIENT_FOLDER
                nuget install packages.config -OutputDirectory packages
                nuget install ./test/packages.config -OutputDirectory packages
                msbuild -version
                msbuild -property:Configuration=Release "cybersource-rest-client-dotnet.sln"
                Write-Output "Build Successful"
                nuget pack cybersource-rest-client-dotnet.nuspec
              shell: pwsh
            - name: Upload Rest Client SDK Nupkg
              uses: actions/upload-artifact@v4
              with:
                name: sdk-nupkg
                path: ${{env.CLIENT_FOLDER}}/*.nupkg
            # To be removed
            - name: Upload Generate Report Action
              uses: actions/upload-artifact@v4
              with:
                name: generate-action
                path: ${{env.CLIENT_FOLDER}}/.github/actions/generate-report/action.yml
    build-the-samples-and-run-tests:
      defaults:
        run:
          shell: bash
      strategy:
        fail-fast: false
        matrix:
          operating-system: [windows-latest,windows-2019]
          net-framework-version: [4.6.1,4.6.2,4.7,4.7.1,4.7.2,4.8,4.8.1]
          exclude:
            - operating-system: windows-2019
              net-framework-version: 4.8.1
            - operating-system: windows-latest
              net-framework-version: 4.6.1
      needs: build-the-dotnet-client # to make sure these jobs only start once the already present jobs are done running
      runs-on: ${{matrix.operating-system}}
      steps:
        - name: Download the Built Rest Client for Dotnet from previous Job
          uses: actions/download-artifact@v4
          with:
            name: sdk-nupkg
            path: sdk-nupkg
        - name: Download the Generate Action
          uses: actions/download-artifact@v4
          with:
            name: generate-action
            path: generate-action
        - name: Checkout cybersource-rest-samples-csharp repo
          uses: actions/checkout@v4
          with:
            repository: 'CyberSource/cybersource-rest-samples-csharp'
            ref: 'master'
            path: ${{env.SAMPLE_FOLDER}}
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v2
        - name: Building the samples and Running the Tests
          run: |
            msbuild -version
            $clientSdkFolderName = (Get-ChildItem -Path sdk-nupkg -Filter "*nupkg" | Select-Object -First 1).BaseName
            $clientSdkVersion = $clientSdkFolderName.Substring(24)
            nuget Sources Add -Name "temperory_nuget_source" -Source ((Get-Location).Path + "\sdk-nupkg")
            cd $Env:SAMPLE_FOLDER
            (Get-Content ./packages.config) | ForEach-Object { $_ -replace '.*<package\s*id="CyberSource\.Rest\.Client".*\/>', "<package id=`"CyberSource.Rest.Client`" version=`"$clientSdkVersion`" targetFramework=`"net461`" />" } | Set-Content ./packages.config
            (Get-Content ./cybersource-rest-samples-csharp.csproj) | ForEach-Object { $_ -replace "(<HintPath>)(.)+(cybersource-rest-client-dotnet.dll</HintPath>)", "<HintPath>packages\\$clientSdkFolderName\\lib\\cybersource-rest-client-dotnet.dll</HintPath>" } | Set-Content ./cybersource-rest-samples-csharp.csproj
            (Get-Content ./cybersource-rest-samples-csharp.csproj) | ForEach-Object { $_ -replace "(<TargetFrameworkVersion>)(.)+(</TargetFrameworkVersion>)", "<TargetFrameworkVersion>v${{matrix.net-framework-version}}</TargetFrameworkVersion>" } | Set-Content ./cybersource-rest-samples-csharp.csproj
            nuget install packages.config -OutputDirectory packages -Source temperory_nuget_source -Source https://api.nuget.org/v3/index.json
            msbuild -property:Configuration=Release "cybersource-rest-samples-csharp.sln"
            cd bin/Release/net461
            Write-Output "Running Samples now"
            ./SampleCode.exe -RunAll > testing_dotnet.log
            Copy-Item ".\testing_dotnet.log" -Destination "..\..\..\"
            Set-Location ..\..\..
            Move-Item -Path .\testing_dotnet.log -Destination .\output.log
          shell: pwsh
        - name: Using Report Generation Action
          id: report-generation
          uses: ./generate-action
          with:
            lang: dotnet
            sample-folder-name: ${{env.SAMPLE_FOLDER}}
            log-file-name: output.log
        - name: Upload Test Reports
          uses: actions/upload-artifact@v4
          with:
            name: sample-run-report-${{matrix.operating-system}}-dotnet-framework-ver-${{matrix.net-framework-version}}
            path: ${{env.SAMPLE_FOLDER}}/${{steps.report-generation.outputs.result-pdf-name}}
